### ISSUE TITLE
ToolTippery support

### ISSUE THREAD

**Issue by ghost** [EIA485/NeosGetItemLink#4]
https://github.com/Psychpsyo/Tooltippery is a really useful thing for my ADHD brain.

I tried to add it manually to the en.json file for the English locale located at https://github.com/Psychpsyo/DefaultTooltips

However I'm barely competent at reading the code and couldn't grok what the button names were other than "button."

If you could get it working and maybe make a getitemlink.json for it that would store in /defaultTooltips/Locales/ that would be cool.

**Comment by EIA485** [comment]
implemented in version [1.3.0](https://github.com/EIA485/NeosGetItemLink/releases/tag/1.3.0.0)
